### ISSUE TITLE
Include Youtube video in documentation

### ISSUE THREAD

**Issue by xandark** [dschmenk/SHR-NTSC#1]
This is one of the most amazing new things I've seen on the GS. 

Just when I thought no new surprises could come out of that hardware which I banged on for years and years, you come up with this marvel, and the Python code is actually readable, very nice!

I just saw the KansasFest 2017 video on this, and I think it'd be a great adjunct to mention in the main readme docs. Could you link to it? https://www.youtube.com/watch?v=S8ZsefIEnvE

**Comment by dschmenk** [comment]
Hi Xandark - thanks for your nice comments. I actually have the links to the YouTube and high quality archive.org videos in the README (I updated the YouTube to match the archive.org version). I hope someone uses this technique in a future demoscene project!

Dave...
